package ro.bithat.dms.smartform.backend;

public enum AttributeLinkDataType {

    NUMERIC, TEXT, DATA, BOOLEAN, TEXTAREA, LABEL, LINE, TITLE, HTML, EMAIL, SYSDATE, HOLOGRAPH, IBAN, CUI, CNP,
    CNP_CUI, OPT_GROUP, OPT_SELECT, OPT_SELECT_MULTIVALUE, OPT_SELECT_DROPBOX, OPT_SELECT_DROPBOX_MULTIVALUE,
    LOCATIE, ADRESA, TELEFON, NUME, STRADA, DATA_ORA, COMPLEX, TARA, JUDET, LOCALITATE, FISIER

}
